version: '3.3'
services:
  chrome:
    image: selenium/standalone-chrome-debug
    container_name: selenium
    ports:
    - "5900:5900"
  wordpressdb:
    image: vindi/mysql-woocommerce-ci
    container_name: wordpress_db
    ports:
    - "3306"
  wordpressweb:
    image: vindi/apache-woocommerce-ci
    container_name: vindi.local
    depends_on:
    - wordpressdb
    ports:
    - "443:443"
    links:
    - wordpressdb:mysql
networks:
  default:
    external:
      name: webproxy
