version: '3.3'
services:
  selenium:
    image: selenium/standalone-chrome-debug
    container_name: selenium
    ports:
    - "4444:4444"
    - "5900:5900"
    volumes:
    - /dev/shm:/dev/shm
  mariadb:
    image: vindi/mysql-magento1-ci
    container_name: magento1_db
    ports:
    - "3306"
  web:
    image: vindi/apache-magento1-dev
    container_name: vindi.local
    env_file:
      - .env
    depends_on:
    - mariadb
    ports:
    - "443:443"
    links:
    - mariadb:mysql
    volumes:
    - ./html:/var/www/html
    - ./html/app/code/community/Vindi/Subscription/tests:/var/www/html/app/code/community/Vindi/Subscription/tests
    working_dir: /var/www/html/app/code/community/Vindi/Subscription/tests
networks:
  default:
    external:
      name: webproxy
